Repository SMU-Algorithm-Study/Algorithm, pull requests merged in 2021-03, with the labels that each got.

#32 week8_Nunu-0
  week8/17471_게리맨더링_Nunu-0.cpp
  week8/2011_암호코드_Nunu-0.java
  week8/6588_골드바흐의 추측_Nunu-0.java
Labels: C++, java

#33 week9_minji-o-j
  week9/3190_뱀_minji-o-j.py
Labels: python

#34 week9_hyeinlee725
  week9/3190_뱀_hyeinlee725.py
Labels: python

#35 week9_Nunu-0
  week9/3190_뱀_Nunu-0.cpp
Labels: C++

#38 week10_minji-o-j
  week10/15954_인형들_minji-o-j.py
Labels: python

#36 week10_hyeinlee725
  week10/15954_인형들_hyeinlee725.py
Labels: python

#37 week10_Nunu-0
  week10/15954_인형들_Nunu-0.java
Labels: java

#39 week11_minji-o-j
  week11/2343_기타 레슨_minji-o-j.py
  week12/16953_A → B_minji-o-j.py
Labels: python

#40 week11_Nunu-0
  week11/2343_기타 레슨_Nunu-0.cpp
Labels: C++

#44 week12_minji-o-j
  week12/16953_A → B_minji-o-j.py
Labels: python

#41 week12_Nunu-0
  week12/16953_A → B_Nunu-0.java
Labels: java
