Repository SMU-Algorithm-Study/Algorithm, pull requests merged in 2021-02, with the labels that each got.

#25 week6_eunhxx
  week6/2168_타일 위의 대각선_eunhxx.py
  week6/5911_선물_eunhxx.py
  week6/9177_단어 섞기_eunhxx.py
Labels: python

#26 week6_hyeinlee725
  week6/2168_타일 위의 대각선_hyeinlee725.py
  week6/5911_선물_hyeinlee725.py
  week6/9177_단어 섞기_hyeinlee725.py
Labels: python

#27 week6_Nunu-0
  week6/2168_타일 위의 대각선_Nunu-0.cpp
  week6/5911_선물_Nunu-0.cpp
  week6/9177_단어 섞기_Nunu-0.cpp
Labels: C++

#24 week6_minji-o-j
  week6/2168_타일 위의 대각선_minji-o-j.py
  week6/5911_선물_minji-o-j.py
  week6/9177_단어 섞기_minji-o-j.py
Labels: python

#28 week7_Nunu-0
  week7/2617_구슬 찾기_Nunu-0.java
  week7/2981_검문_Nunu-0.java
  week7/9252_LCS 2_Nunu-0.cpp
Labels: C++, java

#30 week7_minji-o-j
  week7/2671_구슬 찾기_minji-o-j.py
  week7/2981_검문_minji-o-j.py
  week7/9252_LCS 2_minji-o-j.py
Labels: python

#29 week7_hyeinlee725
  week7/2617_구슬 찾기_hyeinlee725.py
  week7/2981_검문_hyeinlee725.py
  week7/9252_LCS 2_hyeinlee725.py
Labels: python

#31 week8_hyeinlee725
  week8/17471_게리맨더링_hyeinlee725.py
  week8/2011_암호코드_hyeinlee725.py
  week8/6588_골드바흐의 추측_hyeinlee725.py
Labels: python
